#!/bin/bash
set -eu

if [[ -z "$OP_NODE_NETWORK" ]]; then
  echo "expected OP_NODE_NETWORK to be set" 1>&2
  exit 1
fi

# wait until local geth comes up (authed so will return 401 without token)
until [ "$(curl -s -w '%{http_code}' -o /dev/null "${OP_NODE_L2_ENGINE_RPC/ws/http}")" -eq 401 ]; do
  echo "waiting for geth to be ready"
  sleep 5
done

echo "$OP_NODE_L2_ENGINE_AUTH_RAW" > "$OP_NODE_L2_ENGINE_AUTH"

exec ./op-node
